### ISSUE TITLE
Project description and Contribution guide

### ISSUE THREAD

**Issue by RealRichi3** [Jayjerome/GoFundMe-Backend#1]
### Project Description
This project is a backend API for a GoFundMe web app. The app should should allow certain individuals setup crowdfunding projects, each project has to be reviewed by an admin before it becomes available for donations other users should be allowed to make donations to any project of their choice.

### Technology
* Node JS
* Express JS
* Mongo DB

For this we would create a MVC NodeJS app

## PROJECT REQUIREMENTS
* There should be at least three kinds of users (admin, donors, project_owners)
* Only project owners can add a project for crowd funding
* To add a project, the owner has to make a request, except an admin approves the request that project should not be available for donations.
* Project owners should be able to carry out create and certain update actions for their projects
* Users should be able to make donations to projects
* Users should be able to get a list of all available projects
* Users should be able to get a list of all projects he/she has made donations to
* Admins should be able to reject/accept new project request
* Admins should be able to delete a project

## TASKS
- [x] *Setup project structure*
- [x] *Outline templates for pull requests and issues*

### Models
- [x] *Database schema models for all users (donors, admin, project_owners)*
- [x] *Database schema models for projects*

### Middlewares
- [x] *Authentication middleware*
- [ ] *Permissions handler*
- [x] *Error handler middleware*

### Utilities
- [x] *Mail handler (send emails)*

#### Authentication feature
- [x] *Signup*
- [x] *Email verification*
- [x] *Login*
- [x] *Password reset*
- [ ] *Social signin/signup with Google*

#### Projects
- [x] *Create new project*
- [ ] *Submit new project for review*
- [ ] *Review project*
- [x] *Update project details*
- [ ] *Delete project*
- [x] *Make donations*
- [x] *Get list of all projects*
- [x] *Get list of donations made*

### TESTS
- [x] *Authentication tests (signup, login, verifyemail ....)*
- [x] *Permission handler*
- [x] *CRUD operations for projects*
- [x] *Project donation*

#### TESTS/DEPLOYMENT 
- [ ] *API documentation*
- [ ] *App testing and deployment*
- [ ] *Deployment*

## CONTRIBUTING
- If you want to work on any of these tasks, signify by leaving a comment, then you should create a sub issue for the task.
- For each sub issue for any task add a reference to this issue `(ex: Sub issue for #5)`
- When creating an issue for any of these tasks/features please add a description on the feature you intend to implement
- This issue is open to collaboration, your thoughts and suggestions are highly welcome. If you think any task is missing please comment below and it will be added
- All Pull requests relating to any task in this issue should be directed to the `dev` branch
- All Issues should be created using the issue template in `/.github/ISSUE_TEMPLATE.md` [#2](https://github.com/Jayjerome/GoFundMe-Backend/issues/2)
- All Pull request should be made using the Pull request template in `./github/PULL_REQUEST_TEMPLATE.md` [#3](https://github.com/Jayjerome/GoFundMe-Backend/issues/3)

For pull request relating to any task in this issue the title should include `Date [feature or bug]  your title`
